from flask import Flask, render_template, request
from analyzer.detector import detect_phishing
from database.database import create_database, save_scan, get_all_scans
import sqlite3

from flask import send_file
from reportlab.pdfgen import canvas
import os 
import csv

app = Flask(__name__)
create_database()

@app.route("/history")
def history():
    scans = get_all_scans()
    return render_template(
        "history.html",
        scans=scans
    )

@app.route("/dashboard")
def dashboard():

    conn = sqlite3.connect("database/phishguard.db")
    cursor = conn.cursor()

    cursor.execute("SELECT COUNT(*) FROM scan_history")
    total = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM scan_history WHERE risk='High'")
    high = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM scan_history WHERE risk='Medium'")
    medium = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM scan_history WHERE risk='Low'")
    low = cursor.fetchone()[0]

    conn.close()

    return render_template(
        "dashboard.html",
        total=total,
        high=high,
        medium=medium,
        low=low
    )

@app.route("/")
def home():
    return render_template("index.html")


@app.route("/analyze", methods=["POST"])
def analyze():

    email = request.form["email_content"]
    url = request.form["url"]

    result = detect_phishing(email)

    save_scan(
    email,
    url,
    result["score"],
    result["risk"]
)

    return render_template(
        "result.html",
        email=email,
        url=url,
        score=result["score"],
        risk=result["risk"],
        keywords=result["keywords"],
        explanation=result["explanation"]
    )

@app.route("/download-pdf")
def download_pdf():

    pdf_path = "reports/phishing_report.pdf"

    c = canvas.Canvas(pdf_path)

    c.setFont("Helvetica-Bold", 18)
    c.drawString(180, 800, "PhishGuard AI Report")

    c.setFont("Helvetica", 12)
    c.drawString(50, 760, "This report was generated by PhishGuard AI.")
    c.drawString(50, 730, "For complete scan details, check the Scan History page.")

    c.save()

    return send_file(pdf_path, as_attachment=True)

@app.route("/download-csv")
def download_csv():

    scans = get_all_scans()

    csv_path = "reports/scan_history.csv"

    with open(csv_path, "w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)

        writer.writerow([
            "ID",
            "Score",
            "Risk",
            "Date"
        ])

        for scan in scans:
            writer.writerow(scan)

    return send_file(csv_path, as_attachment=True)

@app.route("/help")
def help_page():
    return render_template("help.html")


if __name__ == "__main__":
    app.run(debug=True)